### 1-1

In [8]:
import pandas as pd
from sklearn import datasets

In [16]:
housing = datasets.load_boston()
X=pd.DataFrame(housing['data'],columns=housing['feature_names'])
y=pd.DataFrame(housing['target'],columns=['target'])

c:\Users\hkyoo52\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :func:`~sklearn.datasets.fetch_california_housing`) and the Ames housing
    dataset. You can load the datasets as follows::

        from sklearn.datasets import fetch_california_housing
        housing = fetch_california_housing()

    for the California housing dataset and::

        from sklearn.datasets import fetch_openml
        housing = fetch_openml(name="house_prices", as_frame=True)

    for the Ames housing dataset.
  warnings.warn(msg, category=FutureWarning)

In [17]:
print(X.shape)
print(y.shape)

(506, 13)
(506, 1)

In [24]:
crim = X['CRIM'].sort_values()[-10:].values

In [30]:
big_crim = [i for i in crim if i>80]
anw = sum(big_crim)/len(big_crim)

In [31]:
anw

88.9762

In [39]:
print(X['AGE'].std())
print(X['AGE'].mean())
X['AGE'] = X['AGE'].fillna(X['AGE'].mean())

28.148861406903617
68.57490118577076

0      65.2
1      78.9
2      61.1
3      45.8
4      54.2
       ...
501    69.1
502    76.7
503    91.0
504    89.3
505    80.8
Name: AGE, Length: 506, dtype: float64

In [44]:
X['AGE'][X['AGE']>X['AGE'].mean() + X['AGE'].std()* 1.5]

Series([], Name: AGE, dtype: float64)

In [45]:
X

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier

data=pd.read_csv('../데이터/breast-cancer-wisconsin.csv', encoding='utf-8')
print(data.columns)
X=data[['Clump_Thickness', 'Cell_Size', 'Cell_Shape',
       'Marginal_Adhesion', 'Single_Epithelial_Cell_Size', 'Bare_Nuclei',
       'Bland_Chromatin', 'Normal_Nucleoli', 'Mitoses']]
y=data[['Class']]

X_train,X_test,y_train,y_test = train_test_split(X,y,stratify=y,random_state=52)
min_max = MinMaxScaler()
min_max.fit(X_train)
minmax_train = min_max.transform(X_train)
minmax_test = min_max.transform(X_test)

model = LogisticRegression()
#print(help(GradientBoostingClassifier))
#model=GradientBoostingClassifier()
model.fit(minmax_train,y_train)

prob = model.predict_proba(minmax_test)
anw = pd.concat([X_test,pd.DataFrame(prob[:,1], columns = ['pred'])],axis=1)
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,pd.DataFrame(prob[:,1], columns = ['pred']))
#roc_auc_score(y_test, model.decision_function(minmax_test))

Index(['code', 'Clump_Thickness', 'Cell_Size', 'Cell_Shape',
       'Marginal_Adhesion', 'Single_Epithelial_Cell_Size', 'Bare_Nuclei',
       'Bland_Chromatin', 'Normal_Nucleoli', 'Mitoses', 'Class'],
      dtype='object')

c:\Users\hkyoo52\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.9974474474474474

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import GradientBoostingRegressor

data=pd.read_csv('../데이터/vote.csv',encoding='utf-8')
X_dum = data[['gender', 'region']]
XY=data[['edu', 'income', 'age', 'score_gov',
       'score_progress', 'score_intention', 'vote', 'parties']]
X_dum['gender']=X_dum['gender'].replace([1,2],['male','female'])
X_dum['region']=X_dum['region'].replace([1,2,3,4,5],['1','2','3','4','5'])
X_dum = pd.get_dummies(X_dum)
X=pd.concat([X_dum,XY[['edu', 'income', 'age', 'score_gov',
       'score_progress', 'score_intention']]],axis=1)
y=XY[['vote']]

X_train,X_test,y_train,y_test = train_test_split(X,y,stratify=y,random_state=52)
minmax=MinMaxScaler()
minmax.fit(X_train)
minmax_train = minmax.transform(X_train)
minmax_test = minmax.transform(X_test)

model=LogisticRegression()
#model=GradientBoostingClassifier()
model.fit(minmax_train,y_train)
pred=model.predict_proba(minmax_test)

X_test = X_test.reset_index(drop=True)
prob = pd.DataFrame(pred[:,1],columns=['do_vote']).reset_index(drop=True)
anw = pd.concat([X_test,prob],axis=1).reset_index(drop=True)

anw
#print(roc_auc_score(y_test,prob))

C:\Users\hkyoo52\AppData\Local\Temp\ipykernel_18272\1215832821.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_dum['gender']=X_dum['gender'].replace([1,2],['male','female'])
C:\Users\hkyoo52\AppData\Local\Temp\ipykernel_18272\1215832821.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_dum['region']=X_dum['region'].replace([1,2,3,4,5],['1','2','3','4','5'])
c:\Users\hkyoo52\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,gender_female,gender_male,region_1,region_2,region_3,region_4,region_5,edu,income,age,score_gov,score_progress,score_intention,do_vote
133,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0,2.0,4.0,4.0,3.0,NaN
195,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,NaN
135,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,4.0,2.0,2.0,3.0,NaN
25,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,3.0,2.0,3.2,0.350981
200,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0,2.0,4.0,3.0,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.593459
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.455287
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.640604
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.608964
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.722487